### ISSUE TITLE
想知道为什么我本地用vlc转一个视频为rtsp流后放本地链接上去播放就会报错

### ISSUE THREAD

**Issue by HolyDogs** [yy1261633791/rtsp-web-converter#3]

**Comment by yy1261633791** [comment]
com.converter.factories.ConverterFactories

grabber = new FFmpegFrameGrabber(url);
			if ("rtsp".equals(url.substring(0, 4))) {
				grabber.setOption("rtsp_transport", "tcp");
				grabber.setOption("stimeout", "5000000");
			} else {
				grabber.setOption("timeout", "5000000");
			}

**Comment by HolyDogs** [comment]
还是报错
 ERROR com.converter.factories.ConverterFactories - avformat_open_input() error -135: Could not open input "rtsp://127.0.0.1:8554/qqqq". (Has setFormat() been called?)
org.bytedeco.javacv.FrameGrabber$Exception: avformat_open_input() error -135: Could not open input "rtsp://127.0.0.1:8554/qqqq". (Has setFormat() been called?)
	at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:853) ~[javacv-1.5.1.jar:1.5.1]
	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:785) ~[javacv-1.5.1.jar:1.5.1]
	at com.converter.factories.ConverterFactories.run(ConverterFactories.java:87) ~[classes/:?]

**Comment by yy1261633791** [comment]
你这个流用VLC能播放吗，项目也是启动在本地的吗

**Comment by HolyDogs** [comment]
可以用VLC播放，项目也是本地运行的

**Comment by yy1261633791** [comment]
现已更新，现在对输入没有要求了，您可以再试试！
