### ISSUE TITLE
为什么转出的flv视频流变成了1920*1920的？

### ISSUE THREAD

**Issue by myf-sky** [yy1261633791/rtsp-web-converter#5]
原始视频流是海康摄像头的1920*1080的rtsp流，通过转换后输出的flv流变成了1920*1920的了，请问这是什么原因造成的，需要如何调整后端代码？

**Comment by yy1261633791** [comment]
![image](https://user-images.githubusercontent.com/26320072/92353244-70a83a80-f112-11ea-9447-89eee6557ab3.png)

**Comment by yy1261633791** [comment]
不应该出现高度也是1920的情况啊

**Comment by yy1261633791** [comment]
在com.converter.factories.ConverterTranFactories第80行处理了视频大于1080p的

**Comment by myf-sky** [comment]
我在本地测试将转出的视频流分辨率写成固定的
grabber.setImageWidth(500);
                                grabber.setImageHeight(500);
                                recorder = new FFmpegFrameRecorder(stream, grabber.getImageWidth(), grabber.getImageHeight(),
测试的时候没生效，您帮忙看看是不是改的有问题
![企业微信截图_15994619437433](https://user-images.githubusercontent.com/34133763/92357858-22e40000-f11b-11ea-8c1f-6e6205e422c6.png)
![企业微信截图_15994619876736](https://user-images.githubusercontent.com/34133763/92357871-28414a80-f11b-11ea-92e5-fa0619baa723.png)

**Comment by yy1261633791** [comment]
你加我Q吧：1261633791
